//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiskInspection.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.12.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("21573792")]
        public string Cam1Sn {
            get {
                return ((string)(this["Cam1Sn"]));
            }
            set {
                this["Cam1Sn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Cam2Sn {
            get {
                return ((string)(this["Cam2Sn"]));
            }
            set {
                this["Cam2Sn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("check_disk_debug")]
        public string EndPointDebug {
            get {
                return ((string)(this["EndPointDebug"]));
            }
            set {
                this["EndPointDebug"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("check_service_status")]
        public string EndPointCheckStatus {
            get {
                return ((string)(this["EndPointCheckStatus"]));
            }
            set {
                this["EndPointCheckStatus"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://127.0.0.1:8386/ai")]
        public string ApiUrlAi {
            get {
                return ((string)(this["ApiUrlAi"]));
            }
            set {
                this["ApiUrlAi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("127.0.0.1")]
        public string PlcIp {
            get {
                return ((string)(this["PlcIp"]));
            }
            set {
                this["PlcIp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int Cam1Exposure {
            get {
                return ((int)(this["Cam1Exposure"]));
            }
            set {
                this["Cam1Exposure"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int Cam2Exposure {
            get {
                return ((int)(this["Cam2Exposure"]));
            }
            set {
                this["Cam2Exposure"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SaveEnable {
            get {
                return ((bool)(this["SaveEnable"]));
            }
            set {
                this["SaveEnable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int SaveMode {
            get {
                return ((int)(this["SaveMode"]));
            }
            set {
                this["SaveMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\huynhvc\\OTHERS\\disk_checking\\disk_checking\\APP\\out_test")]
        public string SavePath {
            get {
                return ((string)(this["SavePath"]));
            }
            set {
                this["SavePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8000")]
        public int PlcPort {
            get {
                return ((int)(this["PlcPort"]));
            }
            set {
                this["PlcPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("connect_plc")]
        public string EndpointConnectPlc {
            get {
                return ((string)(this["EndpointConnectPlc"]));
            }
            set {
                this["EndpointConnectPlc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("disconnect_plc")]
        public string EndpointDisconnectPlc {
            get {
                return ((string)(this["EndpointDisconnectPlc"]));
            }
            set {
                this["EndpointDisconnectPlc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("control_uv_light")]
        public string EndpointControlUvLight {
            get {
                return ((string)(this["EndpointControlUvLight"]));
            }
            set {
                this["EndpointControlUvLight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("control_white_light")]
        public string EndpointControlWhiteLight {
            get {
                return ((string)(this["EndpointControlWhiteLight"]));
            }
            set {
                this["EndpointControlWhiteLight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("check_connection")]
        public string EndpointCheckConnection {
            get {
                return ((string)(this["EndpointCheckConnection"]));
            }
            set {
                this["EndpointCheckConnection"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("on_error_abnormal")]
        public string EndpointOnErrorAbnormal {
            get {
                return ((string)(this["EndpointOnErrorAbnormal"]));
            }
            set {
                this["EndpointOnErrorAbnormal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://127.0.0.1:8386/communication")]
        public string ApiUrlCom {
            get {
                return ((string)(this["ApiUrlCom"]));
            }
            set {
                this["ApiUrlCom"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("check_disk_uv_debug")]
        public string EndPointDebugUv {
            get {
                return ((string)(this["EndPointDebugUv"]));
            }
            set {
                this["EndPointDebugUv"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("read_trigger")]
        public string EndpointReadTrigger {
            get {
                return ((string)(this["EndpointReadTrigger"]));
            }
            set {
                this["EndpointReadTrigger"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("reset_trigger")]
        public string EndpointResetTrigger {
            get {
                return ((string)(this["EndpointResetTrigger"]));
            }
            set {
                this["EndpointResetTrigger"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("check_disk_white")]
        public string EndpointInspectWhiteLight {
            get {
                return ((string)(this["EndpointInspectWhiteLight"]));
            }
            set {
                this["EndpointInspectWhiteLight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("check_disk_uv")]
        public string EndpointInspectUvLight {
            get {
                return ((string)(this["EndpointInspectUvLight"]));
            }
            set {
                this["EndpointInspectUvLight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string StartShiftTime {
            get {
                return ((string)(this["StartShiftTime"]));
            }
            set {
                this["StartShiftTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int CurrentOK {
            get {
                return ((int)(this["CurrentOK"]));
            }
            set {
                this["CurrentOK"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int CurrentNG {
            get {
                return ((int)(this["CurrentNG"]));
            }
            set {
                this["CurrentNG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2000")]
        public int WaitWhiteLightOn {
            get {
                return ((int)(this["WaitWhiteLightOn"]));
            }
            set {
                this["WaitWhiteLightOn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5000")]
        public int WaitWhiteLightOff {
            get {
                return ((int)(this["WaitWhiteLightOff"]));
            }
            set {
                this["WaitWhiteLightOff"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2000")]
        public int WaitUvLightOn {
            get {
                return ((int)(this["WaitUvLightOn"]));
            }
            set {
                this["WaitUvLightOn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5000")]
        public int WaitUvLightOff {
            get {
                return ((int)(this["WaitUvLightOff"]));
            }
            set {
                this["WaitUvLightOff"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int SaveOption {
            get {
                return ((int)(this["SaveOption"]));
            }
            set {
                this["SaveOption"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("on_error_mixing")]
        public string EndpointOnErrorMixing {
            get {
                return ((string)(this["EndpointOnErrorMixing"]));
            }
            set {
                this["EndpointOnErrorMixing"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int CurrentWarning {
            get {
                return ((int)(this["CurrentWarning"]));
            }
            set {
                this["CurrentWarning"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("on_ok_signal")]
        public string EndpointOnOkSignal {
            get {
                return ((string)(this["EndpointOnOkSignal"]));
            }
            set {
                this["EndpointOnOkSignal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int DeleteDays {
            get {
                return ((int)(this["DeleteDays"]));
            }
            set {
                this["DeleteDays"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("off_ok_signal")]
        public string EndpointOffOkSignal {
            get {
                return ((string)(this["EndpointOffOkSignal"]));
            }
            set {
                this["EndpointOffOkSignal"] = value;
            }
        }
    }
}
